### PR TITLE
Feature: event selected

### PR DESCRIPTION
**Pull request by paparent**
Hi ! 

In order to have access to the selected element outside the component, I thought it could have an event to send all the selected items.

At first I thought of using `v-model`, but that required more change and I don't know if it's ok to give even more control...

Thanks for that component ! It's useful, don't need to code that anymore 👍

### CODE REVIEW

**Review by syropian — CHANGES_REQUESTED** [review]
Thanks! Could you add a test for this?

Sort of unrelated, but I regret calling that method `itemSelected`, instead of something like `itemIsSelected`, as the former sounds like it would be some kind of event _when_ the item is selected. I might rename and add a deprecation to the old method name 😅

**Comment by paparent** [comment]
@syropian I added a very simple test.. I don't know exactly how to test the feature. and the test syntax is a little weird to my eyes. Comments welcome!

**Comment by syropian** [comment]
@paparent That test looks good to me 👍 

I'm at work right now, but I'll give everything a last look after. I'll probably bundle the method name change with this into the next release and release tonight. Thanks again!

**Review by syropian — APPROVED** [review]

**Comment by syropian** [comment]
Merged and released as `v1.1.0`. Thanks again!

**Pull request merged**
